// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByDF-333v50Bx9HI-Cidc01xhS9ajMI7g',
    appId: '1:665099211508:web:b13f82a71ee455924004a1',
    messagingSenderId: '665099211508',
    projectId: 'ecrafts-c2137',
    authDomain: 'ecrafts-c2137.firebaseapp.com',
    storageBucket: 'ecrafts-c2137.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoQwcw8YESywzRK6m-n2PeSBb5eZzAnPU',
    appId: '1:665099211508:android:4a8b4cad74d761024004a1',
    messagingSenderId: '665099211508',
    projectId: 'ecrafts-c2137',
    storageBucket: 'ecrafts-c2137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzfJfDO-z0FH7hOkOUee4j0Q_qR7HQWtg',
    appId: '1:665099211508:ios:aa92431b28d8604d4004a1',
    messagingSenderId: '665099211508',
    projectId: 'ecrafts-c2137',
    storageBucket: 'ecrafts-c2137.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzfJfDO-z0FH7hOkOUee4j0Q_qR7HQWtg',
    appId: '1:665099211508:ios:aa92431b28d8604d4004a1',
    messagingSenderId: '665099211508',
    projectId: 'ecrafts-c2137',
    storageBucket: 'ecrafts-c2137.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByDF-333v50Bx9HI-Cidc01xhS9ajMI7g',
    appId: '1:665099211508:web:a865030c4b52d1a44004a1',
    messagingSenderId: '665099211508',
    projectId: 'ecrafts-c2137',
    authDomain: 'ecrafts-c2137.firebaseapp.com',
    storageBucket: 'ecrafts-c2137.firebasestorage.app',
  );
}
